### ISSUE TITLE
エラーメッセージ表示の仕組みの共通化

### ISSUE THREAD

**Issue by furuhama** [tnandate/2018-newbies#101]
フロント側に送る json で
{ errors: "hoge" }
みたいなフォーマットで入れる？？

**Comment by kanebest** [comment]
エラー表示すべき箇所
- [ ] ログイン時
- [ ] 情報更新時
- [ ] RemitRequest作成時
  - [ ] メールアドレスが不適な場合
  - [ ] send押下時
- [ ] RemitRequest応答時
  - [ ] Accept時
