### ISSUE TITLE
Charge id が飛び飛びになっている

### ISSUE THREAD

**Issue by furuhama** [tnandate/2018-newbies#119]
Charge.all.count => 1000ちょっと
Charge.last.id => 33000ちょっと
とかになっている

おそらく、 charge 作成時に id を確保して、
処理が失敗したら、 id は利用済みになるものの、レコードは残らない

**Comment by ryoff** [comment]
mysql rollback autoincrement とかの検索ワードで、mysqlの公式documentが出てくるはず 👍 

on duplicate key update 文とかでも、似たような問題ある 🤔 

大きなサービスになってくると、idのmax値に、autoincrementの値が達しないか、とかも監視したりするよ

最近のようにpkがbigintになってる限り、ほぼ大丈夫だけどね
