### ISSUE TITLE
テスト拡充

### ISSUE THREAD

**Issue by furuhama** [tnandate/2018-newbies#131]
- Charge 作成時
  - なんちゃんが stripe api を見ながらテスト書き途中
- RemitRequest 作成, accept, reject, cancel, error

どちらの場合も
アプリケーションと

- stripe
- db
- ユーザー

の整合性を保証する

**Comment by furuhama** [comment]
- balance の境界値テスト
- remit request の accept 時で、相手の balance が境界値付近の時のテスト

**Comment by tnandate** [comment]
Stripe API
- Errorが起こった時想定したレスポンスが返ってくるかの検証
