### ISSUE TITLE
[DO NOT CLOSE] リリース条件

### ISSUE THREAD

**Issue by furuhama** [tnandate/2018-newbies#15]
このアプリをどういう状態にするか、という観点で
目指す状態とそのためのタスクをいくつかのグループと優先度に分類した

- ユーザーの情報や資産がきちんと守られている状態
  - ユーザーの情報や資産が、ユーザーの意図とは別に流出したり操作されたりしない状態

- 想定できないユーザーの挙動がなくなっている状態
  - 各挙動をテスト可能にし、問題を防ぐ
  - 具体例としては以下
    - formの入力値に変なものが入れられても問題ない
    - 変なリクエストを受けても問題ない

- サービスの成長を考えたときにやばそうなところをなくした状態
  - 利用者が増えた時に無理のない状態になっているか
  - ヘビーに利用した場合に無理のない状態になっているか

- ユーザビリティの向上
  - ユーザーが成し遂げたいことを、ストレス少なく成し遂げられる状態

**Comment by kanebest** [comment]
- セキュリティ周り
  - CSRF攻撃への対処
     - https://qiita.com/maruloop/items/e14d02299bd136f4b1fc

**Comment by furuhama** [comment]
https://railsguides.jp/security.html

**Comment by furuhama** [comment]
bye nova
